name: u_maryland
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hooks_riverpod: ^2.3.6
  flutter_hooks: ^0.18.6
  riverpod_annotation: ^2.1.1
  gap: ^3.0.0
  flutter_animate: ^4.1.1+1
  widgetbook: ^3.0.0-beta.14
  widgetbook_annotation: ^3.0.0-beta.7

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.2.1
  widgetbook_generator: ^3.0.0-beta.11

flutter:
  uses-material-design: true
  assets:
    - assets/